name: "Taggear Imagen de docker"
inputs:
  environment:
    type: string
    required: true
    
outputs:
  tagged:
    description: "Nombre completo para la imagen taggeada"
    value: "${{steps.taggear.outputs.tagged}}"
    
runs:
  using: "composite"
  steps:
    - name: "Version"
      id: version
      uses: ./.github/actions/version

    - name: "Nombre app"
      id: name
      uses: ./.github/actions/name-app
        
    - name: "Nombre completo Imagen"
      id: taggear
      shell: bash
      run: |
         echo Entrono: "${{ inputs.environment }}"
         if [[ "${{ inputs.environment }}" == "uat" ]]; then
           tagged_image="${{  steps.name.outputs.name }}:${{ steps.version.outputs.version}}-snapshot"
            echo "Tagged image: $tagged_image"
            echo "tagged=${tagged_image}" >> $GITHUB_OUTPUT
         else
           tagged_image="${{  steps.name.outputs.name }}:${{ steps.version.outputs.version}}"
            echo "Tagged image: $tagged_image"
            echo "tagged=${tagged_image}" >> $GITHUB_OUTPUT
         fi
       
  
