name: "Taggear Imagen de docker"

outputs:
  tagged:
    description: "Nombre completo para la imagen taggeada"
    value: "${{steps.taggear.outputs.tagged}}"
    
runs:
  using: "composite"
  steps:
    - name: "Version"
      id: version
      uses: ./.github/actions/version

    - name: "Nombre app"
      id: name
      uses: ./.github/actions/name-app
        
    - name: "Nombre completo Imagen"
      id: taggear
      shell: bash
      run: |
        tagged_image="${{  steps.name.outputs.name }}:${{ steps.version.outputs.version}}"
        echo "Tagged image: $tagged_image"
        echo "tagged=${tagged_image}" >> $GITHUB_OUTPUT
  
